export const properties = [
  {
    property_id: 9,
    agent: {
      userId: 7,
      role: "agent",
      firstname: "Elena",
      lastname: "Radu",
      email: "elena.radu@homedeal.com",
      password: "1234",
      phoneNumber: 711003344,
      description:
        "Elena este cunoscută pentru intermedierea vânzărilor către românii din diaspora. A contribuit la peste 50 de tranzacții internaționale și are o rețea extinsă de colaboratori externi.",
      document: null,
      profilePicture: "agent7.jpg",
      title: "Lucrează cu clienți din diaspora",
    },
    title: "Casă cu 5 camere în centrul orașului",
    description:
      "Această casă este situată în zona centru și oferă un spațiu generos de 157 m², completat de o curte privată de aproximativ 31 m². Imobilul include 5 camere și 2 băi, aflându-se la etajul 9 dintr-o clădire construită în anul 2004. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "172700",
    type: "Casă",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "9",
    compartmentalization: "Decomandat",
    rooms: 5,
    suitable_for: "Cupluri",
    facilities: [
      "Parc - 300m",
      "Spital - 1km",
      "Grădiniță - 400m",
      "Mall - 2km",
    ],
    bathrooms: 2,
    year: "2004",
    images: "property91.jpg, property92.jpg, property93.jpg",
    area: "Iași",
    surface: 157,
    listing_date: "2025-01-16",
  },
  {
    property_id: 4,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Garsonieră spațioasă în zona Tătărași",
    description:
      "Această garsonieră este situată în zona Tătărași și oferă un spațiu bine compartimentat de 33 m², ideal pentru cei care caută confort urban. Imobilul include o cameră, o baie și o bucătărie, aflându-se la etajul 9 dintr-o clădire construită în anul 2000. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "29700",
    type: "Garsonieră",
    adress: "Strada I.C. Brătianu 22, Tătărași",
    city: "Iași",
    floor: "9",
    compartmentalization: "Semidecomandat",
    rooms: 1,
    suitable_for: "Investitori",
    facilities: [
      "Parc - 300m",
      "Stație autobuz - 200m",
      "Școală - 500m",
      "Magazin - 100m",
    ],
    bathrooms: 1,
    year: "2000",
    images: "property41.jpg, property42.jpg, property43.jpg",
    area: "Tătărași",
    surface: 33,
    listing_date: "2024-07-28",
  },
  {
    property_id: 10,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Apartament cu 4 camere în zona Copou",
    description:
      "Acest apartament este situat în zona Copou și oferă un spațiu generos de 139 m², completat de o curte privată de aproximativ 27 m² unde au acces toți locatarii din bloc. În apropiere se află un parc, ideal pentru momente de relaxare alături de copii. Imobilul include 4 camere și 1 baie, aflându-se la etajul 8 dintr-un bloc construi în anul 1994. Este potrivit pentru cupluri cu copii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "152900",
    type: "Apartament",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "8",
    compartmentalization: "Semidecomandat",
    rooms: 4,
    suitable_for: "Cupluri",
    facilities: [
      "Mall - 2km",
      "Magazin - 100m",
      "Grădiniță - 400m",
      "Metrou - 150m",
    ],
    bathrooms: 1,
    year: "1994",
    images: "property101.jpg, property102.jpg, property103.jpg",
    area: "Copou",
    surface: 139,
    listing_date: "2024-10-15",
  },
  {
    property_id: 11,
    agent: {
      userId: 3,
      role: "agent",
      firstname: "Maria",
      lastname: "Stan",
      email: "maria.stan@homedeal.com",
      password: "1234",
      phoneNumber: 733221100,
      description:
        "Maria lucrează de peste 7 ani în domeniu și are o expertiză solidă în vânzarea de case și vile. A colaborat cu dezvoltatori imobiliari și a consiliat clienți în investiții majore.",
      document: null,
      profilePicture: "agent3.jpg",
      title: "Experiență în case și vile",
    },
    title: "Apartament cu 4 camere în zona Tătărași",
    description:
      "Acest apartament este situat în zona Tătărași și oferă un spațiu generos de 159 m², completat de o curte privată de aproximativ 31 m². Imobilul include 4 camere și 3 băi, aflându-se la etajul 2 dintr-o clădire construită în anul 2006. Este potrivit pentru studenți și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "174900",
    type: "Apartament",
    adress: "Strada I.C. Brătianu 22, Tătărași",
    city: "Iași",
    floor: "2",
    compartmentalization: "Semidecomandat",
    rooms: 4,
    suitable_for: "Studenți",
    facilities: [
      "Parc - 300m",
      "Stație autobuz - 200m",
      "Școală - 500m",
      "Grădiniță - 400m",
    ],
    bathrooms: 3,
    year: "2006",
    images: "property111.jpg, property112.jpg, property113.jpg",
    area: "Tătărași",
    surface: 159,
    listing_date: "2025-02-13",
  },
  {
    property_id: 12,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Apartament cu 4 camere în zona Breazu",
    description:
      "Acest apartament este situat în zona Breazu și oferă un spațiu generos de 151 m², completat de o curte privată de aproximativ 30 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camerăe și 2 baiei, aflându-se la etajul 6 dintr-o clădire construită în anul 2000. Este potrivit pentru familii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "166100",
    type: "Apartament",
    adress: "Strada Căpșunilor 3, Breazu",
    city: "Iași",
    floor: "6",
    compartmentalization: "Semidecomandat",
    rooms: 4,
    suitable_for: "Familii",
    facilities: [
      "Grădiniță - 400m",
      "Mall - 2km",
      "Stație autobuz - 200m",
      "Parc - 300m",
    ],
    bathrooms: 2,
    year: "2000",
    images: "property121.jpg, property122.jpg, property123.jpg",
    area: "Breazu",
    surface: 151,
    listing_date: "2025-02-05",
  },
  {
    property_id: 13,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Casă cu 2 camere în zona Dacia",
    description:
      "Această casă este situată în zona Dacia și oferă un spațiu generos de 76 m², completat de o curte privată de aproximativ 15 m². Imobilul include 2 camere și 1 baie, aflându-se la etajul 2 etaje dintr-o clădire construită în anul 2005. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "91200",
    type: "Casă",
    adress: "Strada Tabacului 18, Dacia",
    city: "Iași",
    floor: "2 etaje",
    compartmentalization: "Semidecomandat",
    rooms: 2,
    suitable_for: "Investitori",
    facilities: [
      "Parc - 300m",
      "Grădiniță - 400m",
      "Mall - 2km",
      "Spital - 1km",
    ],
    bathrooms: 1,
    year: "2005",
    images: "property131.jpg, property132.jpg, property133.jpg",
    area: "Dacia",
    surface: 76,
    listing_date: "2024-08-09",
  },
  {
    property_id: 14,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Casă cu 4 camere în zona Copou",
    description:
      "Această casă este situată în zona Copou și oferă un spațiu generos de 120 m², completat de o curte privată de aproximativ 24 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camerăe și 3 baiei, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 2008. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "144000",
    type: "Casă",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Decomandat",
    rooms: 4,
    suitable_for: "Cupluri",
    facilities: [
      "Metrou - 150m",
      "Mall - 2km",
      "Școală - 500m",
      "Spital - 1km",
    ],
    bathrooms: 3,
    year: "2008",
    images: "property141.jpg, property142.jpg, property143.jpg",
    area: "Copou",
    surface: 120,
    listing_date: "2025-02-18",
  },
  {
    property_id: 7,
    agent: {
      userId: 1,
      role: "agent",
      firstname: "Ana",
      lastname: "Popescu",
      email: "ana.popescu@homedeal.com",
      password: "1234",
      phoneNumber: 722123456,
      description:
        "Ana are o experiență de peste 6 ani în vânzarea apartamentelor cu 2 camere și a gestionat peste 100 de tranzacții de succes. Este recunoscută pentru atenția la detalii și empatia cu nevoile clienților.",
      document: null,
      profilePicture: "agent1.jpg",
      title: "Specialist în apartamente cu 2 camere",
    },
    title: "Apartament cu 4 camere în zona Tătărași",
    description:
      "Acest apartament este situat în zona Tătărași și oferă un spațiu generos de 148 m², ce include o curte privată de aproximativ 29 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camere, o bucătărie și o baie, aflându-se la etajul 10 dintr-o clădire construită în anul 2001. Este potrivit pentru familii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "162800",
    type: "Apartament",
    adress: "Strada I.C. Brătianu 22, Tătărași",
    city: "Iași",
    floor: "10",
    compartmentalization: "Nedecomandat",
    rooms: 4,
    suitable_for: "Familii",
    facilities: [
      "Parc - 300m",
      "Spital - 1km",
      "Școală - 500m",
      "Magazin - 100m",
    ],
    bathrooms: 1,
    year: "2001",
    images: "property71.jpg, property72.jpg, property73.jpg",
    area: "Tătărași",
    surface: 148,
    listing_date: "2025-02-24",
  },
  {
    property_id: 8,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Casă cu 3 camere în zona Copou",
    description:
      "Această casă este situată în zona Copou și oferă un spațiu generos de 101 m², ce include o curte de aproximativ 20 m². Imobilul include 3 camere, o bucătărie și o baie, având 2 etaje. Este potrivit pentru persoane ce doresc să aibă cât mai mult spațiu și să fie totodată aproape de universitate.",
    price: "111100",
    type: "Casă",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "2",
    compartmentalization: "Nedecomandat",
    rooms: 3,
    suitable_for: "Persoane singure",
    facilities: [
      "Spital - 1km",
      "Stație autobuz - 200m",
      "Mall - 2km",
      "Magazin - 100m",
    ],
    bathrooms: 1,
    year: "1991",
    images: "property81.jpg, property82.jpg, property83.jpg",
    area: "Copou",
    surface: 101,
    listing_date: "2024-06-26",
  },
  {
    property_id: 16,
    agent: {
      userId: 1,
      role: "agent",
      firstname: "Ana",
      lastname: "Popescu",
      email: "ana.popescu@homedeal.com",
      password: "1234",
      phoneNumber: 722123456,
      description:
        "Ana are o experiență de peste 6 ani în vânzarea apartamentelor cu 2 camere și a gestionat peste 100 de tranzacții de succes. Este recunoscută pentru atenția la detalii și empatia cu nevoile clienților.",
      document: null,
      profilePicture: "agent1.jpg",
      title: "Specialist în apartamente cu 2 camere",
    },
    title: "Apartament cu 3 camere în zona Copou",
    description:
      "Acest apartament este situat în zona Copou și oferă un spațiu generos de 110 m², completat de o curte privată de aproximativ 22 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 3 camerăe și 3 baiei, aflându-se la etajul 1 dintr-o clădire construită în anul 2015. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "121000",
    type: "Apartament",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "1",
    compartmentalization: "Decomandat",
    rooms: 3,
    suitable_for: "Persoane singure",
    facilities: [
      "Școală - 500m",
      "Stație autobuz - 200m",
      "Mall - 2km",
      "Metrou - 150m",
    ],
    bathrooms: 3,
    year: "2015",
    images: "property161.jpg, property162.jpg, property163.jpg",
    area: "Copou",
    surface: 110,
    listing_date: "2024-10-18",
  },
  {
    property_id: 17,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Garsonieră spațioasă în zona Podu Roș",
    description:
      "Această garsonieră este situată în zona Podu Roș și oferă un spațiu bine compartimentat de 35 m², ideal pentru cei care caută confort urban. Imobilul include 1 camerăă și 1 baie, aflându-se la etajul 3 dintr-o clădire construită în anul 2012. Este potrivit pentru studenți și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "31500",
    type: "Garsonieră",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "3",
    compartmentalization: "Nedecomandat",
    rooms: 1,
    suitable_for: "Studenți",
    facilities: ["Parc - 300m", "Școală - 500m", "Metrou - 150m", "Mall - 2km"],
    bathrooms: 1,
    year: "2012",
    images: "property171.jpg, property172.jpg, property173.jpg",
    area: "Podu Roș",
    surface: 35,
    listing_date: "2024-08-09",
  },
  {
    property_id: 18,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Garsonieră spațioasă în zona Podu Roș",
    description:
      "Această garsonieră este situată în zona Podu Roș și oferă un spațiu bine compartimentat de 39 m², ideal pentru cei care caută confort urban. Imobilul include 1 cameră și 1 baie, aflându-se la etajul 1 dintr-o clădire construită în anul 1998. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "35100",
    type: "Garsonieră",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "1",
    compartmentalization: "Semidecomandat",
    rooms: 1,
    suitable_for: "Persoane singure",
    facilities: [
      "Magazin - 100m",
      "Spital - 1km",
      "Metrou - 150m",
      "Parc - 300m",
    ],
    bathrooms: 1,
    year: "1998",
    images: "property181.jpg, property182.jpg, property183.jpg",
    area: "Podu Roș",
    surface: 39,
    listing_date: "2024-08-17",
  },
  {
    property_id: 19,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Apartament cu 4 camere în zona Galata",
    description:
      "Acest apartament este situat în zona Galata și oferă un spațiu generos de 126 m², completat de o curte privată de aproximativ 25 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camere și 1 baie, aflându-se la etajul 4 dintr-o clădire construită în anul 2013. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "138600",
    type: "Apartament",
    adress: "Strada Dealului 12, Galata",
    city: "Iași",
    floor: "4",
    compartmentalization: "Semidecomandat",
    rooms: 4,
    suitable_for: "Cupluri",
    facilities: ["Metrou - 150m", "Mall - 2km", "Spital - 1km", "Parc - 300m"],
    bathrooms: 1,
    year: "2013",
    images: "property191.jpg, property192.jpg, property193.jpg",
    area: "Galata",
    surface: 126,
    listing_date: "2025-02-21",
  },
  {
    property_id: 6,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Garsonieră spațioasă în centru",
    description:
      "Această garsonieră este situată în zona Independenței și oferă un spațiu bine compartimentat de 39 m², ideal pentru cei care caută să locuiască chiar în centrul orașușui. Imobilul include o cameră și o baie, aflându-se la etajul 6 dintr-o clădire construită în anul 2000. Este potrivit pentru studenți și se remarcă prin finisaje moderne și și de lungă durată.",
    price: "35100",
    type: "Garsonieră",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "6",
    compartmentalization: "Decomandat",
    rooms: 1,
    suitable_for: "Studenți",
    facilities: [
      "Parc - 300m",
      "Metrou - 150m",
      "Grădiniță - 400m",
      "Magazin - 100m",
    ],
    bathrooms: 1,
    year: "2000",
    images: "property61.jpg, property62.jpg, property63.jpg",
    area: "Centru",
    surface: 39,
    listing_date: "2024-09-27",
  },
  {
    property_id: 21,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Apartament cu 5 camere în zona Copou",
    description:
      "Acest apartament este situat în zona Copou și oferă un spațiu generos de 168 m², completat de o curte privată de aproximativ 33 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 5 camere și 3 baie, aflându-se la etajul 8 dintr-o clădire construită în anul 2021. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "184800",
    type: "Apartament",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "8",
    compartmentalization: "Nedecomandat",
    rooms: 5,
    suitable_for: "Cupluri",
    facilities: [
      "Parc - 300m",
      "Școală - 500m",
      "Magazin - 100m",
      "Metrou - 150m",
    ],
    bathrooms: 3,
    year: "2021",
    images: "property211.jpg, property212.jpg, property213.jpg",
    area: "Copou",
    surface: 168,
    listing_date: "2024-12-16",
  },
  {
    property_id: 27,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Apartament cu 2 camere în zona Tătărași",
    description:
      "Acest apartament este situat în zona Tătărași și oferă un spațiu bine compartimentat de 69 m², ideal pentru cei care caută confort urban. Imobilul include 2 camerăe și 1 baie, aflându-se la etajul 8 dintr-o clădire construită în anul 2009. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "75900",
    type: "Apartament",
    adress: "Strada I.C. Brătianu 22, Tătărași",
    city: "Iași",
    floor: "8",
    compartmentalization: "Decomandat",
    rooms: 2,
    suitable_for: "Persoane singure",
    facilities: [
      "Parc - 300m",
      "Mall - 2km",
      "Școală - 500m",
      "Stație autobuz - 200m",
    ],
    bathrooms: 1,
    year: "2009",
    images: "property271.jpg, property272.jpg, property273.jpg",
    area: "Tătărași",
    surface: 69,
    listing_date: "2024-09-11",
  },
  {
    property_id: 28,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Apartament cu 5 camere în zona Dacia",
    description:
      "Acest apartament este situat în zona Dacia și oferă un spațiu generos de 189 m², completat de o curte privată de aproximativ 37 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 5 camere și 1 baie, aflându-se la etajul 6 dintr-o clădire construită în anul 2006. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "207900",
    type: "Apartament",
    adress: "Strada Tabacului 18, Dacia",
    city: "Iași",
    floor: "6",
    compartmentalization: "Decomandat",
    rooms: 5,
    suitable_for: "Cupluri",
    facilities: [
      "Metrou - 150m",
      "Mall - 2km",
      "Magazin - 100m",
      "Parc - 300m",
    ],
    bathrooms: 1,
    year: "2006",
    images: "property281.jpg, property282.jpg, property283.jpg",
    area: "Dacia",
    surface: 189,
    listing_date: "2024-12-29",
  },
  {
    property_id: 29,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Apartament cu 3 camere în zona Breazu",
    description:
      "Acest apartament este situat în zona Breazu și oferă un spațiu generos de 120 m², completat de o curte privată de aproximativ 24 m². Imobilul include 3 camere și 1 baie, aflându-se la etajul 1 dintr-o clădire construită în anul 1998. Este potrivit pentru familii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "132000",
    type: "Apartament",
    adress: "Strada Căpșunilor 3, Breazu",
    city: "Iași",
    floor: "1",
    compartmentalization: "Semidecomandat",
    rooms: 3,
    suitable_for: "Familii",
    facilities: [
      "Mall - 2km",
      "Magazin - 100m",
      "Spital - 1km",
      "Metrou - 150m",
    ],
    bathrooms: 1,
    year: "1998",
    images: "property291.jpg, property292.jpg, property293.jpg",
    area: "Breazu",
    surface: 120,
    listing_date: "2024-12-23",
  },
  {
    property_id: 30,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Apartament cu 4 camere în zona Valea Lupului",
    description:
      "Acest apartament este situat în zona Valea Lupului și oferă un spațiu generos de 130 m², completat de o curte privată de aproximativ 26 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camere și 1 baie, aflându-se la etajul 4 dintr-o clădire construită în anul 2007. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "143000",
    type: "Apartament",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "4",
    compartmentalization: "Decomandat",
    rooms: 4,
    suitable_for: "Investitori",
    facilities: ["Mall - 2km", "Spital - 1km", "Parc - 300m", "Metrou - 150m"],
    bathrooms: 1,
    year: "2007",
    images: "property301.jpg, property302.jpg, property303.jpg",
    area: "Valea Lupului",
    surface: 130,
    listing_date: "2024-12-20",
  },
  {
    property_id: 31,
    agent: {
      userId: 1,
      role: "agent",
      firstname: "Ana",
      lastname: "Popescu",
      email: "ana.popescu@homedeal.com",
      password: "1234",
      phoneNumber: 722123456,
      description:
        "Ana are o experiență de peste 6 ani în vânzarea apartamentelor cu 2 camere și a gestionat peste 100 de tranzacții de succes. Este recunoscută pentru atenția la detalii și empatia cu nevoile clienților.",
      document: null,
      profilePicture: "agent1.jpg",
      title: "Specialist în apartamente cu 2 camere",
    },
    title: "Casă cu 4 camere în zona Breazu",
    description:
      "Această casă este situată în zona Breazu și oferă un spațiu generos de 120 m², completat de o curte privată de aproximativ 24 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camere și 3 băi, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 1993. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "144000",
    type: "Casă",
    adress: "Strada Căpșunilor 3, Breazu",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Decomandat",
    rooms: 4,
    suitable_for: "Investitori",
    facilities: [
      "Magazin - 100m",
      "Metrou - 150m",
      "Școală - 500m",
      "Grădiniță - 400m",
    ],
    bathrooms: 3,
    year: "1993",
    images: "property311.jpg, property312.jpg, property313.jpg",
    area: "Breazu",
    surface: 120,
    listing_date: "2025-03-11",
  },
  {
    property_id: 34,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Garsonieră spațioasă în zona Miroslava",
    description:
      "Această garsonieră este situată în zona Miroslava și oferă un spațiu bine compartimentat de 39 m², ideal pentru cei care caută confort urban. Imobilul include 1 cameră și 1 baie, aflându-se la etajul 7 dintr-o clădire construită în anul 2005. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "35100",
    type: "Garsonieră",
    adress: "Strada Principală 45, Miroslava",
    city: "Iași",
    floor: "7",
    compartmentalization: "Nedecomandat",
    rooms: 1,
    suitable_for: "Investitori",
    facilities: [
      "Grădiniță - 400m",
      "Parc - 300m",
      "Magazin - 100m",
      "Metrou - 150m",
    ],
    bathrooms: 1,
    year: "2005",
    images: "property341.jpg, property342.jpg, property343.jpg",
    area: "Miroslava",
    surface: 39,
    listing_date: "2024-06-04",
  },
  {
    property_id: 35,
    agent: {
      userId: 3,
      role: "agent",
      firstname: "Maria",
      lastname: "Stan",
      email: "maria.stan@homedeal.com",
      password: "1234",
      phoneNumber: 733221100,
      description:
        "Maria lucrează de peste 7 ani în domeniu și are o expertiză solidă în vânzarea de case și vile. A colaborat cu dezvoltatori imobiliari și a consiliat clienți în investiții majore.",
      document: null,
      profilePicture: "agent3.jpg",
      title: "Experiență în case și vile",
    },
    title: "Apartament cu 4 camere în zona Dacia",
    description:
      "Acest apartament este situat în zona Dacia și oferă un spațiu generos de 157 m², completat de o curte privată de aproximativ 31 m². Imobilul include 4 camere și 1 baie, aflându-se la etajul 7 dintr-o clădire construită în anul 2017. Este potrivit pentru studenți și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "172700",
    type: "Apartament",
    adress: "Strada Tabacului 18, Dacia",
    city: "Iași",
    floor: "7",
    compartmentalization: "Nedecomandat",
    rooms: 4,
    suitable_for: "Studenți",
    facilities: [
      "Mall - 2km",
      "Magazin - 100m",
      "Școală - 500m",
      "Parc - 300m",
    ],
    bathrooms: 1,
    year: "2017",
    images: "property351.jpg, property352.jpg, property353.jpg",
    area: "Dacia",
    surface: 157,
    listing_date: "2024-11-01",
  },
  {
    property_id: 36,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Garsonieră spațioasă în zona Galata",
    description:
      "Această garsonieră este situată în zona Galata și oferă un spațiu bine compartimentat de 38 m², ideal pentru cei care caută confort urban. Imobilul include 1 cameră și 1 baie, aflându-se la etajul 10 dintr-o clădire construită în anul 2022. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "34200",
    type: "Garsonieră",
    adress: "Strada Dealului 12, Galata",
    city: "Iași",
    floor: "10",
    compartmentalization: "Semidecomandat",
    rooms: 1,
    suitable_for: "Investitori",
    facilities: [
      "Stație autobuz - 200m",
      "Școală - 500m",
      "Grădiniță - 400m",
      "Magazin - 100m",
    ],
    bathrooms: 1,
    year: "2022",
    images: "property361.jpg, property362.jpg, property363.jpg",
    area: "Galata",
    surface: 38,
    listing_date: "2025-04-18",
  },
  {
    property_id: 2,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Apartament cu 5 camere în zona Dacia",
    description:
      "Acest apartament este situat în zona Dacia și oferă un spațiu generos de 185 m², completat de o curte privată de aproximativ 37 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 5 camere și 3 băi, aflându-se la etajul 5 dintr-o clădire construită în anul 2000. Este potrivit pentru familii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "203500",
    type: "Apartament",
    adress: "Strada Tabacului 18, Dacia",
    city: "Iași",
    floor: "5",
    compartmentalization: "Decomandat",
    rooms: 5,
    suitable_for: "Familii",
    facilities: [
      "Școală - 500m",
      "Grădiniță - 400m",
      "Magazin - 100m",
      "Metrou - 150m",
    ],
    bathrooms: 3,
    year: "2000",
    images: "property21.jpg, property22.jpg, property23.jpg",
    area: "Dacia",
    surface: 185,
    listing_date: "2024-09-03",
  },
  {
    property_id: 3,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Apartament cu 4 camere în zona Galata",
    description:
      "Acest apartament este situat în zona Galata și oferă un spațiu generos de 154 m², completat de o curte privată de aproximativ 30 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camere și 3 băi, aflându-se la etajul 4 dintr-o clădire construită în anul 2005. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "169400",
    type: "Apartament",
    adress: "Strada Dealului 12, Galata",
    city: "Iași",
    floor: "4",
    compartmentalization: "Decomandat",
    rooms: 4,
    suitable_for: "Cupluri",
    facilities: [
      "Stație autobuz - 200m",
      "Parc - 300m",
      "Spital - 1km",
      "Mall - 2km",
    ],
    bathrooms: 3,
    year: "2005",
    images: "property31.jpg, property32.jpg, property33.jpg",
    area: "Galata",
    surface: 154,
    listing_date: "2024-05-31",
  },
  {
    property_id: 20,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Apartament cu 5 camere în zona Dacia",
    description:
      "Acest apartament este situat în zona Dacia și oferă un spațiu generos de 188 m², completat de o curte privată de aproximativ 37 m². Imobilul include 5 camere și 1 baie, aflându-se la etajul 1 dintr-o clădire construită în anul 2024. Este potrivit pentru familii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "206800",
    type: "Apartament",
    adress: "Strada Tabacului 18, Dacia",
    city: "Iași",
    floor: "1",
    compartmentalization: "Decomandat",
    rooms: 5,
    suitable_for: "Familii",
    facilities: [
      "Metrou - 150m",
      "Spital - 1km",
      "Grădiniță - 400m",
      "Mall - 2km",
    ],
    bathrooms: 1,
    year: "2024",
    images: "property201.jpg, property202.jpg, property203.jpg",
    area: "Dacia",
    surface: 188,
    listing_date: "2024-07-18",
  },
  {
    property_id: 42,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Casă cu 4 camere în zona Podu Roș",
    description:
      "Această casă este situată în zona Podu Roș și oferă un spațiu generos de 145 m², completat de o curte privată de aproximativ 29 m². Imobilul include 4 camere și 3 băi, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 2012. Este potrivit pentru familii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "174000",
    type: "Casă",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Semidecomandat",
    rooms: 4,
    suitable_for: "Familii",
    facilities: [
      "Magazin - 100m",
      "Grădiniță - 400m",
      "Metrou - 150m",
      "Spital - 1km",
    ],
    bathrooms: 3,
    year: "2012",
    images: "property421.jpg, property422.jpg, property423.jpg",
    area: "Podu Roș",
    surface: 145,
    listing_date: "2025-04-13",
  },
  {
    property_id: 44,
    agent: {
      userId: 2,
      role: "agent",
      firstname: "Ion",
      lastname: "Ionescu",
      email: "ion.ionescu@homedeal.com",
      password: "1234",
      phoneNumber: 722456789,
      description:
        "Ion a intermediat vânzări de apartamente în zona centrală, având un portofoliu divers și peste 80 de tranzacții finalizate. Este un expert în identificarea celor mai bune oportunități din oraș.",
      document: null,
      profilePicture: "agent2.jpg",
      title: "Lucrează în zona centrală",
    },
    title: "Casă cu 2 camere în zona Valea Lupului",
    description:
      "Această casă este situată în zona Valea Lupului și oferă un spațiu generos de 79 m², completat de o curte privată de aproximativ 15 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 2 camere și 3 băi, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 2001. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "94800",
    type: "Casă",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Decomandat",
    rooms: 2,
    suitable_for: "Bătrâni",
    facilities: [
      "Metrou - 150m",
      "Magazin - 100m",
      "Parc - 300m",
      "Spital - 1km",
    ],
    bathrooms: 3,
    year: "2001",
    images: "property441.jpg, property442.jpg, property443.jpg",
    area: "Valea Lupului",
    surface: 79,
    listing_date: "2025-01-18",
  },
  {
    property_id: 24,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Garsonieră spațioasă în zona Valea Lupului",
    description:
      "Această garsonieră este situată în zona Valea Lupului și oferă un spațiu bine compartimentat de 38 m², ideal pentru cei care caută confort urban. Imobilul include 1 cameră și 1 baie, aflându-se la etajul 8 dintr-o clădire construită în anul 2020. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "34200",
    type: "Garsonieră",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "8",
    compartmentalization: "Decomandat",
    rooms: 1,
    suitable_for: "Persoane singure",
    facilities: [
      "Magazin - 100m",
      "Parc - 300m",
      "Metrou - 150m",
      "Spital - 1km",
    ],
    bathrooms: 1,
    year: "2020",
    images: "property241.jpg, property242.jpg, property243.jpg",
    area: "Valea Lupului",
    surface: 38,
    listing_date: "2025-03-24",
  },
  {
    property_id: 25,
    agent: {
      userId: 2,
      role: "agent",
      firstname: "Ion",
      lastname: "Ionescu",
      email: "ion.ionescu@homedeal.com",
      password: "1234",
      phoneNumber: 722456789,
      description:
        "Ion a intermediat vânzări de apartamente în zona centrală, având un portofoliu divers și peste 80 de tranzacții finalizate. Este un expert în identificarea celor mai bune oportunități din oraș.",
      document: null,
      profilePicture: "agent2.jpg",
      title: "Lucrează în zona centrală",
    },
    title: "Garsonieră spațioasă în zona Galata",
    description:
      "Această garsonieră este situată în zona Galata și oferă un spațiu bine compartimentat de 32 m², ideal pentru cei care caută confort urban. Imobilul include 1 camerăă și 1 baie, aflându-se la etajul 5 dintr-o clădire construită în anul 2000. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "28800",
    type: "Garsonieră",
    adress: "Strada Dealului 12, Galata",
    city: "Iași",
    floor: "5",
    compartmentalization: "Nedecomandat",
    rooms: 1,
    suitable_for: "Investitori",
    facilities: [
      "Parc - 300m",
      "Stație autobuz - 200m",
      "Grădiniță - 400m",
      "Spital - 1km",
    ],
    bathrooms: 1,
    year: "2000",
    images: "property251.jpg, property252.jpg, property253.jpg",
    area: "Galata",
    surface: 32,
    listing_date: "2025-05-07",
  },
  {
    property_id: 49,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Garsonieră în centrul orașului",
    description:
      "Această casă este situată în zona Iași și oferă un spațiu generos de 147 m², completat de o curte privată de aproximativ 29 m². Imobilul include 4 camere și 1 baie, aflându-se la etajul 2 etaje dintr-o clădire construită în anul 2007. Este potrivit pentru familii și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "176400",
    type: "Casă",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "2 etaje",
    compartmentalization: "Semidecomandat",
    rooms: 4,
    suitable_for: "Familii",
    facilities: [
      "Stație autobuz - 200m",
      "Magazin - 100m",
      "Spital - 1km",
      "Școală - 500m",
    ],
    bathrooms: 1,
    year: "2007",
    images: "property491.jpg, property492.jpg, property493.jpg",
    area: "Centru",
    surface: 147,
    listing_date: "2024-12-02",
  },
  {
    property_id: 50,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Casă cu 2 camere în zona Dacia",
    description:
      "Această casă este situată în zona Dacia și oferă un spațiu generos de 65 m², completat de o curte privată de aproximativ 13 m². Imobilul include 2 camere și 1 baie, aflându-se la etajul 2 etaje dintr-o clădire construită în anul 2001. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "78000",
    type: "Casă",
    adress: "Strada Tabacului 18, Dacia",
    city: "Iași",
    floor: "2 etaje",
    compartmentalization: "Nedecomandat",
    rooms: 2,
    suitable_for: "Investitori",
    facilities: [
      "Stație autobuz - 200m",
      "Spital - 1km",
      "Parc - 300m",
      "Magazin - 100m",
    ],
    bathrooms: 1,
    year: "2001",
    images: "property501.jpg, property502.jpg, property503.jpg",
    area: "Dacia",
    surface: 65,
    listing_date: "2024-06-11",
  },
  {
    property_id: 43,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Casă cu 3 camere în zona Bucium",
    description:
      "Această casă este situată în zona Bucium și oferă un spațiu generos de 96 m², completat de o curte privată de aproximativ 19 m². Imobilul include 3 camere și 2 băi, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 1999. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "115200",
    type: "Casă",
    adress: "Șoseaua Bucium 51, Iași",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Nedecomandat",
    rooms: 3,
    suitable_for: "Investitori",
    facilities: [
      "Spital - 1km",
      "Parc - 300m",
      "Școală - 500m",
      "Grădiniță - 400m",
    ],
    bathrooms: 2,
    year: "1999",
    images: "property431.jpg, property432.jpg, property433.jpg",
    area: "Bucium",
    surface: 96,
    listing_date: "2025-05-28",
  },
  {
    property_id: 32,
    agent: {
      userId: 7,
      role: "agent",
      firstname: "Elena",
      lastname: "Radu",
      email: "elena.radu@homedeal.com",
      password: "1234",
      phoneNumber: 711003344,
      description:
        "Elena este cunoscută pentru intermedierea vânzărilor către românii din diaspora. A contribuit la peste 50 de tranzacții internaționale și are o rețea extinsă de colaboratori externi.",
      document: null,
      profilePicture: "agent7.jpg",
      title: "Lucrează cu clienți din diaspora",
    },
    title: "Casă cu 3 camere în zona Galata",
    description:
      "Această casă este situată în zona Galata și oferă un spațiu generos de 95 m², completat de o curte privată de aproximativ 19 m². Imobilul include 3 camere și 1 baie, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 2004. Este potrivit pentru studenți și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "114000",
    type: "Casă",
    adress: "Strada Dealului 12, Galata",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Nedecomandat",
    rooms: 3,
    suitable_for: "Familii",
    facilities: [
      "Spital - 1km",
      "Mall - 2km",
      "Metrou - 150m",
      "Școală - 500m",
    ],
    bathrooms: 1,
    year: "2004",
    images: "property321.jpg, property322.jpg, property323.jpg",
    area: "Galata",
    surface: 95,
    listing_date: "2025-05-17",
  },
  {
    property_id: 15,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Casă cu 2 camere în zona Copou",
    description:
      "Această casă este situată în zona Copou și oferă un spațiu generos de 69 m², completat de o curte privată de aproximativ 13 m². Imobilul include 2 camere și 1 baie, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 2003. Este potrivit pentru studenți și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "82800",
    type: "Casă",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Semidecomandat",
    rooms: 2,
    suitable_for: "Studenți",
    facilities: [
      "Magazin - 100m",
      "Mall - 2km",
      "Spital - 1km",
      "Școală - 500m",
    ],
    bathrooms: 1,
    year: "2003",
    images: "property151.jpg, property152.jpg, property153.jpg",
    area: "Copou",
    surface: 69,
    listing_date: "2025-04-08",
  },
  {
    property_id: 26,
    agent: {
      userId: 6,
      role: "agent",
      firstname: "Mihai",
      lastname: "Vasilescu",
      email: "mihai.vasilescu@homedeal.com",
      password: "1234",
      phoneNumber: 788992233,
      description:
        "Mihai deține un portofoliu important de spații comerciale și este partener de încredere pentru afaceri locale. Are peste 60 de contracte încheiate în domeniul retail și office.",
      document: null,
      profilePicture: "agent6.jpg",
      title: "Agent cu portofoliu comercial",
    },
    title: "Apartament cu 5 camere în zona Iași",
    description:
      "Acest apartament este situat în zona Iași și oferă un spațiu generos de 200 m², completat de o curte privată de aproximativ 40 m². Imobilul include 5 camere și 1 baie, aflându-se la etajul 1 dintr-o clădire construită în anul 2018. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "220000",
    type: "Apartament",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "1",
    compartmentalization: "Nedecomandat",
    rooms: 5,
    suitable_for: "Cupluri",
    facilities: [
      "Metrou - 150m",
      "Spital - 1km",
      "Școală - 500m",
      "Stație autobuz - 200m",
    ],
    bathrooms: 1,
    year: "2018",
    images: "property261.jpg, property262.jpg, property263.jpg",
    area: "Iași",
    surface: 200,
    listing_date: "2024-08-07",
  },
  {
    property_id: 37,
    agent: {
      userId: 1,
      role: "agent",
      firstname: "Ana",
      lastname: "Popescu",
      email: "ana.popescu@homedeal.com",
      password: "1234",
      phoneNumber: 722123456,
      description:
        "Ana are o experiență de peste 6 ani în vânzarea apartamentelor cu 2 camere și a gestionat peste 100 de tranzacții de succes. Este recunoscută pentru atenția la detalii și empatia cu nevoile clienților.",
      document: null,
      profilePicture: "agent1.jpg",
      title: "Specialist în apartamente cu 2 camere",
    },
    title: "Garsonieră spațioasă în zona Breazu",
    description:
      "Această garsonieră este situată în zona Breazu și oferă un spațiu bine compartimentat de 36 m², ideal pentru cei care caută confort urban. Imobilul include 1 cameră și 1 baie, aflându-se la etajul Parter dintr-o clădire construită în anul 1994. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "32400",
    type: "Garsonieră",
    adress: "Strada Căpșunilor 3, Breazu",
    city: "Iași",
    floor: "Parter",
    compartmentalization: "Nedecomandat",
    rooms: 1,
    suitable_for: "Persoane singure",
    facilities: [
      "Grădiniță - 400m",
      "Mall - 2km",
      "Parc - 300m",
      "Școală - 500m",
    ],
    bathrooms: 1,
    year: "1994",
    images: "property371.jpg, property372.jpg, property373.jpg",
    area: "Breazu",
    surface: 36,
    listing_date: "2025-03-12",
  },
  {
    property_id: 38,
    agent: {
      userId: 7,
      role: "agent",
      firstname: "Elena",
      lastname: "Radu",
      email: "elena.radu@homedeal.com",
      password: "1234",
      phoneNumber: 711003344,
      description:
        "Elena este cunoscută pentru intermedierea vânzărilor către românii din diaspora. A contribuit la peste 50 de tranzacții internaționale și are o rețea extinsă de colaboratori externi.",
      document: null,
      profilePicture: "agent7.jpg",
      title: "Lucrează cu clienți din diaspora",
    },
    title: "Casă cu 3 camere în zona Podu Roș",
    description:
      "Această casă este situată în zona Podu Roș și oferă un spațiu generos de 107 m², completat de o curte privată de aproximativ 21 m². Imobilul include 3 camere și 3 băi, aflându-se la etajul 2 etaje dintr-o clădire construită în anul 2005. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "128400",
    type: "Casă",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "2 etaje",
    compartmentalization: "Semidecomandat",
    rooms: 3,
    suitable_for: "Cupluri",
    facilities: [
      "Mall - 2km",
      "Spital - 1km",
      "Școală - 500m",
      "Magazin - 100m",
    ],
    bathrooms: 3,
    year: "2005",
    images: "property381.jpg, property382.jpg, property383.jpg",
    area: "Podu Roș",
    surface: 107,
    listing_date: "2025-05-13",
  },
  {
    property_id: 39,
    agent: {
      userId: 1,
      role: "agent",
      firstname: "Ana",
      lastname: "Popescu",
      email: "ana.popescu@homedeal.com",
      password: "1234",
      phoneNumber: 722123456,
      description:
        "Ana are o experiență de peste 6 ani în vânzarea apartamentelor cu 2 camere și a gestionat peste 100 de tranzacții de succes. Este recunoscută pentru atenția la detalii și empatia cu nevoile clienților.",
      document: null,
      profilePicture: "agent1.jpg",
      title: "Specialist în apartamente cu 2 camere",
    },
    title: "Apartament cu 4 camere în zona Copou",
    description:
      "Acest apartament este situat în zona Copou și oferă un spațiu generos de 130 m², completat de o curte privată de aproximativ 26 m². Imobilul include 4 camere și 3 băi, aflându-se la etajul Parter dintr-o clădire construită în anul 2009. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "143000",
    type: "Apartament",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "Parter",
    compartmentalization: "Decomandat",
    rooms: 4,
    suitable_for: "Investitori",
    facilities: [
      "Magazin - 100m",
      "Metrou - 150m",
      "Spital - 1km",
      "Școală - 500m",
    ],
    bathrooms: 3,
    year: "2009",
    images: "property391.jpg, property392.jpg, property393.jpg",
    area: "Copou",
    surface: 130,
    listing_date: "2024-07-27",
  },
  {
    property_id: 40,
    agent: {
      userId: 2,
      role: "agent",
      firstname: "Ion",
      lastname: "Ionescu",
      email: "ion.ionescu@homedeal.com",
      password: "1234",
      phoneNumber: 722456789,
      description:
        "Ion a intermediat vânzări de apartamente în zona centrală, având un portofoliu divers și peste 80 de tranzacții finalizate. Este un expert în identificarea celor mai bune oportunități din oraș.",
      document: null,
      profilePicture: "agent2.jpg",
      title: "Lucrează în zona centrală",
    },
    title: "Garsonieră spațioasă în zona Miroslava",
    description:
      "Această garsonieră este situată în zona Miroslava și oferă un spațiu bine compartimentat de 34 m², ideal pentru cei care caută confort urban. Imobilul include 1 cameră și 1 baie, aflându-se la etajul Parter dintr-o clădire construită în anul 2020. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "30600",
    type: "Garsonieră",
    adress: "Strada Principală 45, Miroslava",
    city: "Iași",
    floor: "Parter",
    compartmentalization: "Decomandat",
    rooms: 1,
    suitable_for: "Investitori",
    facilities: [
      "Școală - 500m",
      "Spital - 1km",
      "Mall - 2km",
      "Magazin - 100m",
    ],
    bathrooms: 1,
    year: "2020",
    images: "property401.jpg, property402.jpg, property403.jpg",
    area: "Miroslava",
    surface: 34,
    listing_date: "2025-01-05",
  },
  {
    property_id: 41,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Apartament cu 4 camere în zona Tătărași",
    description:
      "Acest apartament este situat în zona Tătărași și oferă un spațiu generos de 134 m², completat de o curte privată de aproximativ 26 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 4 camere și 3 băi, aflându-se la etajul Parter dintr-o clădire construită în anul 1998. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "147400",
    type: "Apartament",
    adress: "Strada I.C. Brătianu 22, Tătărași",
    city: "Iași",
    floor: "Parter",
    compartmentalization: "Semidecomandat",
    rooms: 4,
    suitable_for: "Persoane singure",
    facilities: [
      "Spital - 1km",
      "Grădiniță - 400m",
      "Parc - 300m",
      "Stație autobuz - 200m",
    ],
    bathrooms: 3,
    year: "1998",
    images: "property411.jpg, property412.jpg, property413.jpg",
    area: "Tătărași",
    surface: 134,
    listing_date: "2025-03-05",
  },
  {
    property_id: 33,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Apartament cu 5 camere în zona Miroslava",
    description:
      "Acest apartament este situat în zona Miroslava și oferă un spațiu generos de 190 m², completat de o curte privată de aproximativ 38 m². Imobilul include 5 camerăe și 2 baiei, aflându-se la etajul 1 dintr-o clădire construită în anul 1991. Este potrivit pentru investitori și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "209000",
    type: "Apartament",
    adress: "Strada Principală 45, Miroslava",
    city: "Iași",
    floor: "1",
    compartmentalization: "Decomandat",
    rooms: 5,
    suitable_for: "Investitori",
    facilities: [
      "Metrou - 150m",
      "Școală - 500m",
      "Stație autobuz - 200m",
      "Magazin - 100m",
    ],
    bathrooms: 2,
    year: "1991",
    images: "property331.jpg, property332.jpg, property333.jpg",
    area: "Miroslava",
    surface: 190,
    listing_date: "2024-12-30",
  },
  {
    property_id: 1,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Garsonieră spațioasă în zona Breazu",
    description:
      "Această garsonieră este situată în zona Breazu și oferă un spațiu bine compartimentat de 40 m², ideal pentru cei care caută confort urban. Imobilul include 1 cameră și 1 baie, aflându-se la etajul 3 dintr-o clădire construită în anul 2001. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "36000",
    type: "Garsonieră",
    adress: "Strada Căpșunilor 3, Breazu",
    city: "Iași",
    floor: "3",
    compartmentalization: "Semidecomandat",
    rooms: 1,
    suitable_for: "Persoane singure",
    facilities: [
      "Magazin - 100m",
      "Grădiniță - 400m",
      "Metrou - 150m",
      "Școală - 500m",
    ],
    bathrooms: 1,
    year: "2001",
    images: "property11.jpg, property12.jpg, property13.jpg",
    area: "Breazu",
    surface: 40,
    listing_date: "2024-09-04",
  },
  {
    property_id: 22,
    agent: {
      userId: 4,
      role: "agent",
      firstname: "Alexandru",
      lastname: "Nistor",
      email: "alex.nistor@homedeal.com",
      password: "1234",
      phoneNumber: 744332211,
      description:
        "Alexandru cunoaște în detaliu zona Copou și a sprijinit peste 70 de clienți în achiziția de locuințe aici. Este un consultant de încredere pentru familiile care caută siguranță și confort.",
      document: null,
      profilePicture: "agent4.jpg",
      title: "Consultant în zona Copou",
    },
    title: "Apartament cu 4 camere în zona Tătărași",
    description:
      "Acest apartament este situat în zona Tătărași și oferă un spațiu generos de 140 m², completat de o curte privată de aproximativ 28 m². Imobilul include 4 camere și 1 baie, aflându-se la etajul 3 dintr-o clădire construită în anul 2008. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "154000",
    type: "Apartament",
    adress: "Strada I.C. Brătianu 22, Tătărași",
    city: "Iași",
    floor: "3",
    compartmentalization: "Nedecomandat",
    rooms: 4,
    suitable_for: "Cupluri",
    facilities: [
      "Grădiniță - 400m",
      "Stație autobuz - 200m",
      "Parc - 300m",
      "Mall - 2km",
    ],
    bathrooms: 1,
    year: "2008",
    images: "property221.jpg, property222.jpg, property223.jpg",
    area: "Tătărași",
    surface: 140,
    listing_date: "2025-02-16",
  },
  {
    property_id: 23,
    agent: {
      userId: 3,
      role: "agent",
      firstname: "Maria",
      lastname: "Stan",
      email: "maria.stan@homedeal.com",
      password: "1234",
      phoneNumber: 733221100,
      description:
        "Maria lucrează de peste 7 ani în domeniu și are o expertiză solidă în vânzarea de case și vile. A colaborat cu dezvoltatori imobiliari și a consiliat clienți în investiții majore.",
      document: null,
      profilePicture: "agent3.jpg",
      title: "Experiență în case și vile",
    },
    title: "Apartament cu 5 camere în zona Podu Roș",
    description:
      "Acest apartament este situat în zona Podu Roș și oferă un spațiu generos de 180 m², completat de o curte privată de aproximativ 36 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 5 camere și 1 baie, aflându-se la etajul 6 dintr-o clădire construită în anul 2007. Este potrivit pentru studenți și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "198000",
    type: "Apartament",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "6",
    compartmentalization: "Nedecomandat",
    rooms: 5,
    suitable_for: "Studenți",
    facilities: [
      "Spital - 1km",
      "Metrou - 150m",
      "Școală - 500m",
      "Grădiniță - 400m",
    ],
    bathrooms: 1,
    year: "2007",
    images: "property231.jpg, property232.jpg, property233.jpg",
    area: "Podu Roș",
    surface: 180,
    listing_date: "2025-04-24",
  },
  {
    property_id: 5,
    agent: {
      userId: 7,
      role: "agent",
      firstname: "Elena",
      lastname: "Radu",
      email: "elena.radu@homedeal.com",
      password: "1234",
      phoneNumber: 711003344,
      description:
        "Elena este cunoscută pentru intermedierea vânzărilor către românii din diaspora. A contribuit la peste 50 de tranzacții internaționale și are o rețea extinsă de colaboratori externi.",
      document: null,
      profilePicture: "agent7.jpg",
      title: "Lucrează cu clienți din diaspora",
    },
    title: "Apartament cu 2 camere în zona Dacia",
    description:
      "Acest apartament este situat în zona Dacia și oferă un spațiu bine compartimentat de 79 m², ideal pentru cei care caută confort urban. Imobilul include 2 camere, o bucătărie și 2 băi, aflându-se la etajul 6 dintr-o clădire cu 6 etaje. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant, situată într-o zonă în care ai acces rapid la tot ce ai nevoie ",
    price: "86900",
    type: "Apartament",
    adress: "Strada Tabacului 18, Dacia",
    city: "Iași",
    floor: "6",
    compartmentalization: "Decomandat",
    rooms: 2,
    suitable_for: "Persoane singure",
    facilities: [
      "Grădiniță - 400m",
      "Spital - 1km",
      "Magazin - 100m",
      "Mall - 2km",
    ],
    bathrooms: 2,
    year: "2021",
    images: "property51.jpg, property52.jpg, property53.jpg",
    area: "Dacia",
    surface: 79,
    listing_date: "2025-02-17",
  },
  {
    property_id: 45,
    agent: {
      userId: 5,
      role: "agent",
      firstname: "Cristina",
      lastname: "Tudor",
      email: "cristina.tudor@homedeal.com",
      password: "1234",
      phoneNumber: 766554433,
      description:
        "Cristina este specializată în chirii pentru studenți și a colaborat cu universități pentru a oferi soluții avantajoase. A asistat la închirierea a peste 120 de apartamente.",
      document: null,
      profilePicture: "agent5.jpg",
      title: "Consultant pentru chirii studențești",
    },
    title: "Casă cu 4 camere în zona Iași",
    description:
      "Această casă este situată în zona Iași și oferă un spațiu generos de 154 m², completat de o curte privată de aproximativ 30 m². Imobilul include 4 camere și 1 baie, aflându-se la etajul 2 etaje dintr-o clădire construită în anul 1993. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "184800",
    type: "Casă",
    adress: "Strada Independenței 1, Iași",
    city: "Iași",
    floor: "2 etaje",
    compartmentalization: "Nedecomandat",
    rooms: 4,
    suitable_for: "Persoane singure",
    facilities: [
      "Grădiniță - 400m",
      "Școală - 500m",
      "Magazin - 100m",
      "Stație autobuz - 200m",
    ],
    bathrooms: 1,
    year: "1993",
    images: "property451.jpg, property452.jpg, property453.jpg",
    area: "Iași",
    surface: 154,
    listing_date: "2025-02-03",
  },
  {
    property_id: 46,
    agent: {
      userId: 7,
      role: "agent",
      firstname: "Elena",
      lastname: "Radu",
      email: "elena.radu@homedeal.com",
      password: "1234",
      phoneNumber: 711003344,
      description:
        "Elena este cunoscută pentru intermedierea vânzărilor către românii din diaspora. A contribuit la peste 50 de tranzacții internaționale și are o rețea extinsă de colaboratori externi.",
      document: null,
      profilePicture: "agent7.jpg",
      title: "Lucrează cu clienți din diaspora",
    },
    title: "Casă cu 5 camere în zona Miroslava",
    description:
      "Această casă este situată în zona Miroslava și oferă un spațiu generos de 151 m², completat de o curte privată de aproximativ 30 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 5 camere și 2 băi, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 2006. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "181200",
    type: "Casă",
    adress: "Strada Principală 45, Miroslava",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Nedecomandat",
    rooms: 5,
    suitable_for: "Cupluri",
    facilities: [
      "Parc - 300m",
      "Grădiniță - 400m",
      "Spital - 1km",
      "Mall - 2km",
    ],
    bathrooms: 2,
    year: "2006",
    images: "property461.jpg, property462.jpg, property463.jpg",
    area: "Miroslava",
    surface: 151,
    listing_date: "2024-11-12",
  },
  {
    property_id: 47,
    agent: {
      userId: 8,
      role: "agent",
      firstname: "Andrei",
      lastname: "Barbu",
      email: "andrei.barbu@homedeal.com",
      password: "1234",
      phoneNumber: 700998877,
      description:
        "Andrei acoperă zona metropolitană și se ocupă exclusiv de clienți care caută locuințe în dezvoltările noi. A participat activ la peste 90 de achiziții în zone rezidențiale moderne.",
      document: null,
      profilePicture: "agent8.jpg",
      title: "Agent exclusiv în zona metropolitană",
    },
    title: "Casă cu 2 camere în zona Galata",
    description:
      "Această casă este situată în zona Galata și oferă un spațiu generos de 63 m², completat de o curte privată de aproximativ 12 m². În apropiere se află un râu liniștit, ideal pentru momente de relaxare. Imobilul include 2 camere și 1 baie, aflându-se la etajul 2 etaje dintr-o clădire construită în anul 1998. Este potrivit pentru persoane singure și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "75600",
    type: "Casă",
    adress: "Strada Dealului 12, Galata",
    city: "Iași",
    floor: "2 etaje",
    compartmentalization: "Decomandat",
    rooms: 2,
    suitable_for: "Persoane singure",
    facilities: [
      "Grădiniță - 400m",
      "Spital - 1km",
      "Metrou - 150m",
      "Stație autobuz - 200m",
    ],
    bathrooms: 1,
    year: "1998",
    images: "property471.jpg, property472.jpg, property473.jpg",
    area: "Galata",
    surface: 63,
    listing_date: "2024-11-22",
  },
  {
    property_id: 48,
    agent: {
      userId: 2,
      role: "agent",
      firstname: "Ion",
      lastname: "Ionescu",
      email: "ion.ionescu@homedeal.com",
      password: "1234",
      phoneNumber: 722456789,
      description:
        "Ion a intermediat vânzări de apartamente în zona centrală, având un portofoliu divers și peste 80 de tranzacții finalizate. Este un expert în identificarea celor mai bune oportunități din oraș.",
      document: null,
      profilePicture: "agent2.jpg",
      title: "Lucrează în zona centrală",
    },
    title: "Casă cu 3 camere în zona Copou",
    description:
      "Această casă este situată în zona Copou și oferă un spațiu generos de 96 m², completat de o curte privată de aproximativ 19 m². Imobilul include 3 camere și 2 băi, aflându-se la etajul 1 etaj dintr-o clădire construită în anul 2021. Este potrivit pentru cupluri și se remarcă prin finisaje moderne și un stil interior elegant.",
    price: "115200",
    type: "Casă",
    adress: "Aleea Copou 8, Copou",
    city: "Iași",
    floor: "1 etaj",
    compartmentalization: "Decomandat",
    rooms: 3,
    suitable_for: "Cupluri",
    facilities: [
      "Școală - 500m",
      "Stație autobuz - 200m",
      "Magazin - 100m",
      "Grădiniță - 400m",
    ],
    bathrooms: 2,
    year: "2021",
    images: "property481.jpg, property482.jpg, property483.jpg",
    area: "Copou",
    surface: 96,
    listing_date: "2024-06-01",
  },
];
